PROJECT = client_websocket_twitter
PROJECT_DESCRIPTION = Client Twitter Like DOSP
PROJECT_VERSION = 0.1.0

DEPS = cowboy
dep_cowboy_commit = 2.6.3

DEP_PLUGINS = cowboy

BUILD_DEPS += relx
include erlang.mk
